version: "3.7"

services:
    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins
        privileged: true
        user: root
        restart: always
        networks:
            - network
        ports:
            - 8081:8080
            - 50000:50000
        volumes:
            - jenkins:/var/jenkins_home
networks:
    network:
volumes:
    jenkins:
        driver: local
