version: "3.7"

services:
    mongo:
        image: mongo
        container_name: mongo
        environment:
            MONGO_INITDB_DATABASE: db
            MONGO_INITDB_ROOT_PASSWORD: P4ssW0rd!
            MONGO_INITDB_ROOT_USERNAME: admin
        networks:
            - network
        ports:
            - 27017:27017
        volumes:
            - mongo:/data/db
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        depends_on:
            - mongo
        environment:
            ME_CONFIG_BASICAUTH_PASSWORD: P4ssW0rd!
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: P4ssW0rd!
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
        networks:
            - network
        ports:
            - 8081:8081
networks:
    network:
volumes:
    mongo:
        driver: local
