version: "3.7"

services:
    neo4j:
        image: neo4j
        container_name: neo4j
        networks:
            - network
        ports:
            - 7474:7474
            - 7687:7687
        volumes:
            - neo4j:/data
networks:
    network:
volumes:
    neo4j:
        driver: local
